import "./MainContent.css";

function MainContent() {
    return (
        <>
            <div className="mainContent">
                <h2>Main Content</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sagittis placerat nunc, non rutrum lacus accumsan a. Maecenas laoreet suscipit massa, sed aliquet eros mollis sit amet. Fusce euismod pharetra felis ac semper. Suspendisse vitae mi augue. Maecenas id elit ac urna gravida faucibus quis id ligula. Sed tellus nunc, congue et sem non, vulputate finibus justo. Curabitur urna lorem, ullamcorper at justo maximus, interdum ultrices est. Integer ornare, orci non volutpat laoreet, quam ipsum interdum nunc, vel consequat ante est gravida risus. Cras eleifend nisl porttitor urna laoreet, id iaculis diam imperdiet. Maecenas blandit posuere lorem, sit amet porta lacus. Sed tempor sem vitae metus cursus, a tempus risus volutpat. Vestibulum et libero diam. In congue sapien eget aliquet pellentesque. Mauris maximus felis lobortis feugiat molestie. Mauris blandit eros nec ornare feugiat.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a pellentesque odio. Etiam semper tortor quis bibendum placerat. Sed a turpis luctus turpis pellentesque luctus at dictum massa. Nam at arcu ut mauris auctor tincidunt. Curabitur ut consectetur nulla. Nunc ut tempus urna. Etiam efficitur nisl ac odio ornare tempus. Phasellus in lorem feugiat, elementum erat at, bibendum purus. Ut euismod malesuada massa sed egestas. Curabitur fringilla felis ex, sed molestie ipsum ornare id. Phasellus vel augue tortor. Etiam nec accumsan purus. Phasellus in urna iaculis, tincidunt magna pretium, fringilla tortor. Donec imperdiet diam volutpat sapien congue ullamcorper eu sit amet justo. Quisque pharetra nunc et turpis rhoncus, ac euismod velit luctus.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sagittis placerat nunc, non rutrum lacus accumsan a. Maecenas laoreet suscipit massa, sed aliquet eros mollis sit amet. Fusce euismod pharetra felis ac semper. Suspendisse vitae mi augue. Maecenas id elit ac urna gravida faucibus quis id ligula. Sed tellus nunc, congue et sem non, vulputate finibus justo. Curabitur urna lorem, ullamcorper at justo maximus, interdum ultrices est. Integer ornare, orci non volutpat laoreet, quam ipsum interdum nunc, vel consequat ante est gravida risus. Cras eleifend nisl porttitor urna laoreet, id iaculis diam imperdiet. Maecenas blandit posuere lorem, sit amet porta lacus. Sed tempor sem vitae metus cursus, a tempus risus volutpat. Vestibulum et libero diam. In congue sapien eget aliquet pellentesque. Mauris maximus felis lobortis feugiat molestie. Mauris blandit eros nec ornare feugiat.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a pellentesque odio. Etiam semper tortor quis bibendum placerat. Sed a turpis luctus turpis pellentesque luctus at dictum massa. Nam at arcu ut mauris auctor tincidunt. Curabitur ut consectetur nulla. Nunc ut tempus urna. Etiam efficitur nisl ac odio ornare tempus. Phasellus in lorem feugiat, elementum erat at, bibendum purus. Ut euismod malesuada massa sed egestas. Curabitur fringilla felis ex, sed molestie ipsum ornare id. Phasellus vel augue tortor. Etiam nec accumsan purus. Phasellus in urna iaculis, tincidunt magna pretium, fringilla tortor. Donec imperdiet diam volutpat sapien congue ullamcorper eu sit amet justo. Quisque pharetra nunc et turpis rhoncus, ac euismod velit luctus.</p>
            </div>
        </>
    );
}

export default MainContent;
